<?php
/**
 * @file
 * Code for the Restaurant Menu feature.
 */

include_once 'restaurant_menu.features.inc';

/**
 * Implements hook_menu().
 */
function restaurant_menu_menu() {
  $items['admin/menus/add'] = array(
    'title' => 'Add Menu',
    'page callback' => 'restaurant_menu_add_menu_admin',
    'access arguments' => array('administer menus'),
    'file' => 'restaurant_menu.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function restaurant_menu_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'admin/menus/add' on 'admin/menus' page.
  if ($root_path == 'admin/menus') {
    $item = menu_get_item('admin/menus/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implements hook_permission().
 */
function restaurant_menu_permission() {
  return array(
    'administer menus' => array(
      'title' => t('Administer Menus'),
      'description' => t('Access the menu admininstration pages and manage menus.'),
    ),
  );
}

/**
 * Implements hook_preprocess().
 */
function restaurant_menu_preprocess_views_view_table(&$variables) {
  $view = $variables['view'];
  if ($view->name == 'administration_menus') {
    // Add css.
    drupal_add_css(drupal_get_path('module', 'restaurant_menu') . '/css/restaurant_menu.css');
  }
}
